### ISSUE TITLE
Decouple car and world logic

### ISSUE THREAD

**Issue by merberich** [Moov-Organization/demo2#1]
World should only be a container for data (graph description + car states) and a ferry of information.
Cars should determine logical state via Solidity contracts and interactions with current world state, perform path planning and execute motion on graph edges.

**Comment by nathikazad** [comment]
What about collision detection where would the logic for that reside and what would be the hook to run that logic?
https://docs.google.com/document/d/192XTKQ0d5yldzmigkX6AGUd3Zr1fn-fv41yaVETvikE/edit
Could you please add to this document, the changes in architecture?

**Comment by merberich** [comment]
Architecture description updated. Collision avoidance logic should be run in the Movement Update Solver block within `Car`. If we want extra safety, we can have `World` run a collision check after receiving all movement update requests, but that shouldn't be necessary if we get the car logic right.
