### ISSUE TITLE
Decide how we will define start and end locations in Solidity

### ISSUE THREAD

**Issue by merberich** [Moov-Organization/demo2#5]
Since the Solidity contract for the bid process includes start location, end location, and bid amount, we will need to determine how cars will interpret start + end location. This can be as easy as saying they will be reported in pixel units.

I think there should be a mapping function, and we can leave that mapping trivial until any point where we need to do modification:
```Go
func solToMapCoords(solX, solY float64) (mapX, mapY uint) {
    mapX = solX
    mapY = solY
    return
}
```

**Comment by nathikazad** [comment]
Yea, I am not entirely sure about the benefits of doing a transform as the image size will be fixed. And more importantly I am not sure about the opportunity cost.

In the mean time, I have written a doc outlining the basis off this transaction here 
https://docs.google.com/document/d/1d-qS_WOLm0BpWYixifSpfDTjOSW0qZaoCo87LF7NPP4/edit

User will call contract function along the lines of, contract.createRideRequest(string from, string to, amount)

**Comment by nathikazad** [comment]
So pixel values for now, till we do cost-analysis of doing a mapping.

**Comment by merberich** [comment]
Closing this as we have formally (codified contract) set the bid coordinate system as a one-to-one mapping to pixel units on the map.
